[build]
  publish = "build"  # The folder that contains your built files
  command = "npm run build"  # The command to build your project

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200